name: ANEMOTION
favicon: null
layout_spectrum: 0.06318
typography_spectrum: 0.30145
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#382531'
    - '#ffffff'
    - '#f4d4cc'
    - '#d8aeac'
    - '#9d9179'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
